### ISSUE TITLE
multipolygon encoding

### ISSUE THREAD

**Issue by tmcw** [springmeyer/geojsonp#2]
something is awry with multipolygon encoding - unlike the rest of examples, it's larger as a pbf than as geojson:

![image](https://cloud.githubusercontent.com/assets/32314/3515911/685ad1a4-06da-11e4-81f3-cc8c7e3e9841.png)

**Comment by springmeyer** [comment]
my hunch is that is the expected result. It is important for arrays (e.g. repeated items) in protobuf to be `packed` for maximum efficiency. Because only native types can be packed and this proto uses custom types for the arrays, this sample proto is, so far, just an example of the simplest and least optimized approach to encoding for pbf. I planned next to compare to a packed flat array, but have not gotten around to that code example. As context, in vector tiles we use a single, packed array for geometries which is much more efficient: https://github.com/mapbox/mapnik-vector-tile/blob/6ed7f9f8495bf04e13808e068125a543a53280bf/proto/vector_tile.proto#L62
